### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by ajkeith** [CHAD-Analytics/CHAD#17]
**Describe the bug**
"We continue to have issues with the data; it is often missing days of data for some bases, and when data is missing all model predictions are unavailable.  At times we have filled those gaps and created our own graphs when that happens." from Mr. McKelvey on 22 Apr

**Additional context**
Issue added from email, @himey97, please feel free to elaborate.

**Comment by galarcon0308** [comment]
I believe this has already been resolved. Partial issue was with negative daily cases (this was fixed) but the larger issue I think was with certain bases (like DM) being further than 50 miles from the centroid of their county, therefore registering no counties in range and no data. I haven't been able to replicate this issue since. Will need more information from the user on actual bases and distances. 

Closing for now.

**Comment by himey97** [comment]
Switching to the new data source (JHU) fixed the missing data issues

**Comment by ajkeith** [comment]
Great to hear! Thanks
