### ISSUE TITLE
Faster Load Times

### ISSUE THREAD

**Issue by tleonard6** [CHAD-Analytics/CHAD#50]
From the higher ups

"I always have to load, stop it, then reload to get it to load."

Do the settings on the server need to be modified to account for traffic or something of that nature?

**Comment by galarcon0308** [comment]
I modified the settings at the start for this but might need some more tweaking. I'll look at a couple things.

**Comment by galarcon0308** [comment]
Increasing the idle instance timeout might help but requires a server restart so I'll try that during not peak usage times

**Comment by galarcon0308** [comment]
Waking the server from sleeping requires the app to go through the startup process for that instance. Decreasing the load on startup will fix this. The all base table in MAJCOM summary is going to be swapped for a similar table with COVID metrics instead of projection information. Testing has shown a large decrease in startup time.
