### ISSUE TITLE
Active Case from JHU download

### ISSUE THREAD

**Issue by galarcon0308** [CHAD-Analytics/CHAD#55]
**Describe the bug**
this new add-in for active cases requires pulling a a new file with a different name every day. Current code uses previous date to pull file. This can cause an error and crash the server when they haven't updated towards the night and the file name is now 2 days old.

**Proposed Fix**
Either tryCatch statement to use 2 days back if one day back fails, and skip file entirely if both fail. Another way is to find the date of the latest file from the server but I don't have those skills yet.

**Comment by levilott** [comment]
I'm not sure if I'll be much help but I'm happy to try! Which code is the JHU code? I'm looking in covid19/www/4_load_external_data/ but I cant tell which file is specific to JHU.

**Comment by galarcon0308** [comment]
covid19/www/4_load_external_data/01_StateInfo.R

Its at line 25 where it is all commented out. Normally there is a curdate <- Sys.Date() - 1 there which sometimes needs to be 2 if its late in the day. The hope is to pull the latest no matter the time of the day without having to guess the proper date.

Thanks for the help man! No worries if you can't, but always appreciate the extra hand!

**Comment by levilott** [comment]
The code below will go to the github folder and pull the most recent date from the file extensions and add that date to the raw extension. This should eliminate the need to rely on the SyS.Date() or "today's date". It should consistently automatically pull the most recent file available regardless of the time the code is executed.

Hope this helps! Let me know if I can jump on a call and trouble shoot.

#CHAD is pulling based on system date and subtracting a day or perhaps 2 depending on the time they update
#The github for the JHU data only has 1 file per date and the most recent is always at the bottom
#Rather than rely on system date or "today's date" I want to:
#Capture all the links from the appropriate github folder
#Read in the link that is 1 from the bottom which should be the newest (the very bottom is "Read.me" file)

#Need the following packages

library(xml2)
library(rvest)
library(dplyr)
library(plyr)
library(readr)
library(naniar)

#Create Left/Right/Mid functions similar to excel as they do not naturally exist in R

left = function(text, num_char) {
  substr(text, 1, num_char)
}

mid = function(text, start_num, num_char) {
  substr(text, start_num, start_num + num_char - 1)
}

right = function(text, num_char) {
  substr(text, nchar(text) - (num_char-1), nchar(text))
}

#Using JHU Github folder for US projections
#Can also use this here for world projections "https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports" 
URL <- "https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports_us"

#capture full page
pg <- read_html(URL)

#capture just the "clickable" extensions
extensions <- html_attr(html_nodes(pg, "a"), "href")

#You can look at this data frame for all extensions on the page
#Looking here the most recent update is 17 rows away from the bottom rather than just 1 row
#There were additional links on the page after the "Read.me" file (generic links at the bottom of the page not files)
#As long as the github page set up does not change the most recent file should consistently be 17 rows away from the last row
extensions <- as.data.frame(extensions)

#Make into data frame and pull the 17th row from the bottom which should consistently be our most recent file
Most_Recent_Extension <- as.data.frame(extensions[(nrow(extensions)-17), ])

#We could attempt to follow extensions and go to the next two pages down the line and pull the raw file
#However its probably easier to just update the "raw" link with the most recently populated date from the available extensions
#Will just capture the most recent date in the folder rather than attempt to follow links

#Convert to character to enable use of left/right functions
#This is a weird column name could rename if desired
Most_Recent_Extension$`extensions[(nrow(extensions) - 17), ]` <- as.character(Most_Recent_Extension$`extensions[(nrow(extensions) - 17), ]`)

#Capture date from most recent file in folder
Date <- left(right(Most_Recent_Extension[1,],14),10)

#Add this date to the "raw" link
#In the future we could also explore going down the extensions to arrive at the raw file but its easy enough to call it out here
Most_Recent_Link <- paste0("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports_us/",Date,".csv")

#Read in the most recent data
Most_Recent_data <- read.csv(Most_Recent_Link)

**Comment by levilott** [comment]
The comment section broke the lines up on the code pieces a little differently and it doesnt seem like I can attach a .R file here. Is there another place that is easier to offer code updates? I'm still pretty new to using github.

**Comment by galarcon0308** [comment]
Nvm I couldn't do it, seems I don't know GitHub that well either haha. You can always make a branch and do a pull requests and we can merge the changes. Here is fine also

**Comment by tleonard6** [comment]
@levilott this worked great!  thank you for taking the time to figure this out!
